[package]
description = "A bindgen-generated Rust wrapper around the DataStax Cassandra C++ driver plus working examples. You probably want to use the \"cassandra-cpp\" crate which provides a safe wrapper."
documentation = "https://docs.rs/cassandra-sys-rs"
# no homepage yet
repository = "https://github.com/Metaswitch/cassandra-sys-rs"
readme = "README.md"
keywords = ["Cassandra", "binding", "CQL", "client", "database" ]
categories = [ "api-bindings", "database", "external-ffi-bindings" ]
license = "Apache-2.0"
name = "cassandra-cpp-sys"
version = "0.8.8"
authors = ["Tupshin Harper <tupshin@tupshin.com>", "Keith Wansbrough <Keith.Wansbrough@metaswitch.com>"]
build = "build.rs"

[badges]
travis-ci = { repository = "Metaswitch/cassandra-sys-rs" }

[lib]
name = "cassandra_cpp_sys"

[[bin]]
name="basic"
path="src/examples/basic.rs"

[[bin]]
name="batch"
path="src/examples/batch.rs"

[[bin]]
name="bind_by_name"
path="src/examples/bind_by_name.rs"

# [[bin]]
# name="callbacks"
# path="src/examples/callbacks.rs"

[[bin]]
name="collections"
path="src/examples/collections.rs"

[[bin]]
name="logging"
path="src/examples/logging.rs"

[[bin]]
name="maps"
path="src/examples/maps.rs"

[[bin]]
name="named_parameters"
path="src/examples/named_parameters.rs"

# [[bin]]
# name="perf"
# path="src/examples/perf.rs"

[[bin]]
name="prepared"
path="src/examples/prepared.rs"

[[bin]]
name="paging"
path="src/examples/paging.rs"

[[bin]]
name="schema_meta"
path="src/examples/schema_meta.rs"

[[bin]]
name="simple"
path="src/examples/simple.rs"

[[bin]]
name="ssl"
path="src/examples/ssl.rs"

[[bin]]
name="tuple"
path="src/examples/tuple.rs"

[[bin]]
name="udt"
path="src/examples/udt.rs"

[[bin]]
name="uuid"
path="src/examples/uuid.rs"

[[bin]]
name="async"
path="src/examples/async.rs"

[dependencies]
libc = "0.2"
num = "0.1"
log = "0.3"
env_logger = "0.3"
error-chain = "0.7"

# clippy = {version = "*", optional = true}

[features]
default=[]
